api/urls.py
from django.urls import path
from . import views

app_name = 'api'
urlpatterns = [
    path('', views.payment, name='payment'),
    path(hallo/, views.makepayment, name= 'hallo'
    ]

asas/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, re_path

from .views import asas, deta, commint, change_friend, home, friend_like, like_post, delete, view_friend, sher, book, \
    post, book_home, add_page, book_list, pages_detal

app_name = 'asas'
urlpatterns = [
    path('', asas, name='asas'),
    path('deta/', deta, name='deta'),
    path('home/', home, name='home'),
    path('commint/', commint, name='commints'),
    path('admin/', admin.site.urls),
    path('commints/<str:pk_test>', commint, name='commint'),
    path('connect/<str:operation>/<str:pk>', change_friend, name='change_friend'),
    path('like/<str:operation>/<str:pk>', friend_like, name='friend_like'),
    path('delete/<str:pk>', delete, name='delete_comment'),
    path('likes/', like_post, name='like_post'),
    path('view_friend/', view_friend, name='view_friend'),
    path('share/', book, name='share'),
    path('page/<str:pk>', post, name='page'),
    path('book/', book_home, name='book'),
    path('add_page1/<str:pk>', post, name='add_page1'),
    path('add_page/<str:operation>/<str:pk>', add_page, name='add_page'),
    path('book_list/', book_list, name='book_list'),
    path('pages_detal/<str:pk>', pages_detal, name='pages_detal'),
    #path('add_pa/', add_pa, name='add_pa')
    # url(r'^commint/{<slug:post>}/$', commint, name='commint'),

]

book/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
# noinspection PyUnresolvedReferences
from abook.views import login, regaster, abut, reg, logout, view_profile, add_profile, edit_profile, profile

#from abook.views import view_profile, add_profile, edit_profile

urlpatterns = [
    #path('post/', post, name='post'),

    path('abut/', abut, name='abut'),
    path('login/', login, name='login'),
    path('regaster/', regaster, name='regaster'),
    path('admin/', admin.site.urls),
    path("reg/", reg, name="reg"),
    path('logout/', logout, name='logout'),
    path('accaont/', include('accaont.urls', namespace='accaont')),
    path('profile/', view_profile, name='profile'),
    #url(r'^frofile/{?p<pk>\d+}/$', frofile, name='frofile_with_pk')
    path('asas/', include('asas.urls', namespace='asas')),
    path('profile/<str:pk_test>', profile, name='find_profiles'),
    path('add_profile/', add_profile, name='add_profile'),
    path('edit_profile/', edit_profile, name='edit_profile'),
    path('paymant/', include('paymant.urls', namespace='paymant')),
    path('shopping_cart/', include('memberships.urls', namespace='shopping_cart')),
    #path('courses/', include('courses.urls', namespace='courses')),
    path('video/', include('video.urls', namespace='video')),
    path('', include('api.urls', namespace='api')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

memberships/urls.py
from django.conf.urls import url

from .views import (
    add_to_cart,
    delete_from_cart,
    order_details,
    checkout,
    update_transaction_records,
    success
)

app_name = 'shopping_cart'

urlpatterns = [
    url(r'^add-to-cart/(?P<item_id>[-\w]+)/$', add_to_cart, name="add_to_cart"),
    url(r'^order-summary/$', order_details, name="order_summary"),
    url(r'^success/$', success, name='purchase_success'),
    url(r'^item/delete/(?P<item_id>[-\w]+)/$', delete_from_cart, name='delete_item'),
    url(r'^checkout/$', checkout, name='checkout'),
    url(r'^update-transaction/(?P<token>[-\w]+)/$', update_transaction_records,
        name='update_records')
]

memberships/models.py
from __future__ import unicode_literals

from django.db import models

from abook.models import Profile
from asas.models import Book


class OrderItem(models.Model):
    product = models.OneToOneField(Book, on_delete=models.SET_NULL, null=True)
    is_ordered = models.BooleanField(default=False)
    date_added = models.DateTimeField(auto_now=True)
    date_ordered = models.DateTimeField(null=True)

    def __str__(self):
        return self.product.name


class Order(models.Model):
    ref_code = models.CharField(max_length=15)
    owner = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True)
    is_ordered = models.BooleanField(default=False)
    items = models.ManyToManyField(OrderItem)
    date_ordered = models.DateTimeField(auto_now=True)

    def get_cart_items(self):
        return self.items.all()

    def get_cart_total(self):
        return sum([item.product.price for item in self.items.all()])

    def __str__(self):
        return '{0} - {1}'.format(self.owner, self.ref_code)


class Transaction(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    token = models.CharField(max_length=120)
    order_id = models.CharField(max_length=120)
    amount = models.DecimalField(max_digits=60, decimal_places=2)
    success = models.BooleanField(default=True)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    image= models.TextField()

    def __str__(self):
        return self.order_id

    class Meta:
        ordering = ['-timestamp']

memberships/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.mail import message
from django.urls import reverse
from django.shortcuts import render, redirect, get_object_or_404

from abook.models import Profile
from asas.models import Book

from .extras import generate_order_id, transact, generate_client_token
from .models import OrderItem, Order, Transaction

import datetime
import stripe

stripe.api_key = settings.STRIPE_SECRET_KEY


def get_user_pending_order(request):
    # get order for the correct user
    user_profile = get_object_or_404(Profile, user=request.user)
    order = Order.objects.filter(owner=user_profile, is_ordered=False)
    if order.exists():
        # get the only order in the list of filtered orders
        return order[0]
    return 0


@login_required()
def add_to_cart(request, **kwargs):
    # get the user profile
    user_profile = get_object_or_404(Profile, user=request.user)
    # filter products by id
    product = Book.objects.filter(id=kwargs.get('item_id', "")).first()
    # check if the user already owns this product
    if product in request.user.profile.ebooks.all():
        messages.info(request, 'You already own this ebook')
        return redirect(reverse('asas:book_list'))
        # create orderItem of the selected product
    order_item, status = OrderItem.objects.get_or_create(product=product)
    # create order associated with the user
    user_order, status = Order.objects.get_or_create(owner=user_profile, is_ordered=False)
    user_order.items.add(order_item)
    if status:
        # generate a reference code
        user_order.ref_code = generate_order_id()
        user_order.save()

    # show confirmation message and redirect back to the same page
    messages.info(request, "item added to cart")
    return redirect(reverse('asas:book_list'))


@login_required()
def delete_from_cart(request, item_id):
    item_to_delete = OrderItem.objects.filter(pk=item_id)
    if item_to_delete.exists():
        item_to_delete[0].delete()
        messages.info(request, "Item has been deleted")
    return redirect(reverse('shopping_cart:order_summary'))


@login_required()
def order_details(request, **kwargs):
    existing_order = get_user_pending_order(request)
    context = {
        'order': existing_order
    }
    return render(request, 'memberships/order_summary.html', context)


@login_required()
def checkout(request, **kwargs):
    #client_token = generate_client_token()
    existing_order = get_user_pending_order(request)
    publishKey = settings.STRIPE_PUBLISHABLE_KEY
    if request.method == 'POST':
        token = request.POST.get('stripeToken')
        if token:
            try:
                charge = stripe.Charge.create(
                    amount=100 * existing_order.get_cart_total(),
                    currency='usd',
                    description='Example charge',
                    source=token,
                )

                return redirect(reverse('shopping_cart:update_records',
                                        kwargs={
                                            'token': token
                                        })
                                )
            except stripe.CardError as e:
                message.info(request, "Your card has been declined.")
        else:
            result = transact({
                'amount': existing_order.get_cart_total(),
                'payment_method_nonce': request.POST['payment_method_nonce'],
                'options': {
                    "submit_for_settlement": True
                }
            })

            if result.is_success or result.transaction:
                return redirect(reverse('shopping_cart:update_records',
                                        kwargs={
                                            'token': result.transaction.id
                                        })
                                )
            else:
                for x in result.errors.deep_errors:
                    messages.info(request, x)
                return redirect(reverse('shopping_cart:checkout'))

    context = {
        'order': existing_order,
        #'client_token': client_token,
        'STRIPE_PUBLISHABLE_KEY': publishKey
    }

    return render(request, 'memberships/checkout.html', context)


@login_required()
def update_transaction_records(request, token):
    # get the order being processed
    order_to_purchase = get_user_pending_order(request)

    # update the placed order
    order_to_purchase.is_ordered = True
    order_to_purchase.date_ordered = datetime.datetime.now()
    order_to_purchase.save()

    # get all items in the order - generates a queryset
    order_items = order_to_purchase.items.all()

    # update order items
    order_items.update(is_ordered=True, date_ordered=datetime.datetime.now())

    # Add products to user profile
    user_profile = get_object_or_404(Profile, user=request.user)
    # get the products from the items
    order_products = [item.product for item in order_items]
    user_profile.ebooks.add(*order_products)
    user_profile.save()

    # create a transaction
    transaction = Transaction(profile=request.user.profile,
                              token=token,
                              order_id=order_to_purchase.id,
                              amount=order_to_purchase.get_cart_total(),
                              success=True)
    # save the transcation (otherwise doesn't exist)
    transaction.save()

    # send an email to the customer
    # look at tutorial on how to send emails with sendgrid
    messages.info(request, "Thank you! Your purchase was successful!")
    return redirect(reverse('book:profile'))


def success(request, **kwargs):
    # a view signifying the transcation was successful
    return render(request, 'shopping_cart/purchase_success.html', {})

memberships/templates/memberships/membership_list.html
{% extends 'courses/base.html' %}


{% block content %}
<div class="container">
	<h1>Select a membership</h1>
	<div class="row">
		{% for object in object %}
		<div class="col-sm-4 col-md-4">
			<h2>{{ object.porm }}</h2>
			<p>Price: $ {{ object.price }}<small>/month</small></p>
			<h4>Included Courses</h4>
			<ul>
				{% for course in object.course_set.all %}
					<li>{{ course.title }}</li>
				{% endfor %}
			</ul>
			{% if object.membership_type != 'Free' %}
			<form method="POST" action="{% url 'memberships:select' %}">
				{% csrf_token %}
				{% if object.membership_type != current_membership %}
					<button class="btn btn-warning">Select</button>
				{% else %}
					<small>This is your current membership</small>
				{% endif %}
				<input type="hidden" name="membership_type" value="{{ object.membership_type }}">
			</form>
			{% endif %}
		</div>
		{% endfor %}
	</div>
</div>



{% endblock content %}

memberships/templates/memberships/order_summary.html
{% extends "base.html" %}

{% block content %}

 <section>
   <div class="row">
    <table class="table table-hover table-bordered text-center">
      <tr class="text-center">
        <th>no.</th>
        <th>Item</th>
        <th>Price</th>
      </tr>
      {% for item in order.get_cart_items %}
        <tr>
          <td>{{ forloop.counter }}</td>
          <td>
            {{ item.product.name }}
            <span class="pull-right">
              <a href="{% url 'shopping_cart:delete_item' item.id %}" data-balloon="remove this item from cart" class="text-danger" onclick="return confirm_delete();">
                <i class="fas fa-trash"></i>
              </a>
            </span>
          </td>
          <td>{{ item.product.price }}</td>
        </tr>
      {% empty %}
        <tr>
          <td colspan= 3> You have not added any items yet.</td>
        </tr>
      {% endfor %}
      <tr>
        {% if order.get_cart_total != None %}
        <td colspan=2>
          <strong class="pull-right">Order Total:</strong>
        </td>

        <td colspan= 1>
          $<strong>{{ order.get_cart_total }}</strong>
        </td>
        {% endif %}
      </tr>
      <tr>
        <td colspan=1 >
          <a href="{% url 'asas:book_list' %}" class="btn btn-warning pull-left">
            {% if order %}Continue Shopping{% else %}Add Items to Cart {% endif %}
          </a>
        </td>
        <td colspan=2>
          {% if order.get_cart_items %}
            <a href="{% url 'shopping_cart:checkout' %}" class="pull-right btn btn-primary">Proceed To Checkout</a>
          {% endif %}
        </td>
      </tr>
    </table>

   </div>
 </section>
{% endblock %}

{% block scripts %}
  {{ block.super }}
  <script>
  function confirm_delete(){
    return confirm("Do you want to remove this item from cart?");
  }
  </script>
{% endblock scripts %}

memberships/templates/memberships/profile.html
{% extends 'courses/base.html' %}


{% block content %}
<div class="container">
	<div class="row">
		<h1>My Profile</h1>
		<div class="col-sm-4 col-md-4">
			{% if user_subscription != None %}
				<h4>Current Membership: {{ user_membership.membership.membership_type }} <small>since {{ user_subscription.get_created_date }}</small></h4>

				{% if user_subscription.active != False %}
					<p>Next payment due: {{ user_subscription.get_next_billing_date }}</p>
					<a href="{% url 'memberships:cancel' %}">Cancel subscription</a>

				{% else %}
					<p>You don't have an active membership plan. Check them out here
						<a href="{% url 'memberships:select' %}"></a>
					</p>
				{% endif %}
			{% endif %}
		</div>
	</div>
</div>
{% endblock content %}

memberships/templates/memberships/purchase_success.html
{% extends 'base.html' %}

{% block content %}
    <h1>Thank you for your purchase!</h1>
    <a href="{% url 'book:book_list' %}">Head back home</a>
{% endblock content %}